### ISSUE TITLE
Consider dash-versions as pre-release

### ISSUE THREAD

**Issue by jdreesen** [bfred-it/tiny-version-compare#2]
On https://github.com/matomo-org/matomo it shows `3.5.1-b2` as latest, while it should be `3.5.1` instead.

**Comment by fregante** [comment]
I think `-` sub-versions should be handled differently. Currently it just considers it a `.`, but npm uses `-` as pre-releases so it's not really correct.

Live demo: https://runkit.com/embed/3untr13sjuc7

**Comment by jdreesen** [comment]
Same for https://github.com/davidkpiano/xstate: it shows `v4.0.0-15` (pre) as latest but latest is `v4.0.0` (final).
