### ISSUE TITLE
Handling invalid version strings

### ISSUE THREAD

**Issue by notlmn** [bfred-it/tiny-version-compare#3]
Example: https://github.com/facebook/graphql (using RGH)

Any plan on supporting this, because this is supposed to be a _tiny_ library.

_People at Facebook should be really crazy_

**Comment by fregante** [comment]
There's no way that will ever be supported. The issue is that this is a compare function, it can't also filter these out.

It could however have an additional `isSupported` function to be used as `arr.filter(compare.isSupported).sort(compare)`

**Comment by notlmn** [comment]
Closing this as there is no way to support version strings that are not server-like.
