### ISSUE TITLE
Kotlin Releases

### ISSUE THREAD

**Issue by yakov116** [bfred-it/tiny-version-compare#4]
https://github.com/JetBrains/kotlin

Dont know if there is anything you can do... 
I think they switched their release numbers at one point

**Comment by fregante** [comment]
It looks about right now, doesn't it?

<img width="298" alt="screenshot 2018-11-10 at 13 48 23" src="https://user-images.githubusercontent.com/1402241/48298401-5473ec00-e4ef-11e8-94ed-56a4fc225bce.png">

**Comment by yakov116** [comment]
@bfred-it great job!!

**Comment by yakov116** [comment]
@bfred-it but the last one was 1.3.0 .....

Side note 
```<a class="border-0 Label--outline-green" href="/JetBrains/kotlin/releases/latest">Latest release</a>```

looks like that will always take you to the last release.

Going to `/org/repo/releases/latest`

**Comment by fregante** [comment]
Latest could be a beta

Also now that’s been fixed further, dash sub-versions are treated as subreleases so Refined GitHub will show 1.3 next time it’s deployed
